name: Build release
on:
  push:
    branches:
    - master
jobs:
  release_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version
      id: bumptag
      uses: anothrNick/github-tag-action@1.22.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: 'patch'
        DRY_RUN: true
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install cargo-release
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-release
        version: "0.13.5"
    - name: Make a release
      uses: actions-rs/cargo@v1
      with:
        command: release
        args: --skip-publish --no-confirm ${{ steps.bumptag.outputs.new_tag }}
